# docker-compose.yaml
version: '3.8'

#networks:
#  shared_network:
#    driver: bridge

services:

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#    networks:
#      - shared_network

  redis:
    image: "redis:alpine"
#    networks:
#      - shared_network


  rabbitmq:
    image: "rabbitmq:3-management-alpine"
#    networks:
#      - shared_network

  celery:
    build: .
    command: celery -A SimpleChatRooms worker -P threads --concurrency=4 --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - USEPOSTGRES=1
#    networks:
#      - shared_network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
#    networks:
#      - shared_network

  web:
    build: .
    command:
      - /bin/bash
      - -c
      - |
        python manage.py migrate
        uvicorn SimpleChatRooms.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - rabbitmq
      - prometheus
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - USEPOSTGRES=1
#    networks:
#      - shared_network

volumes:
    postgres_data:
